# Linear Algebra on Pytorch 

-Instructor: M.Sc.Saul Calderon.

- Authors: 
    - Saúl Calderón, Mauro Méndez, Manuel Zumbado. 

## Install Dependencies

In [ ]:
# Since Collab is being used, it is necessary to install Pytorch
!pip install torch

## Sum, substraction, element wise division and multiplication of vectors

In [9]:
import torch as torch

device = torch.device("cpu") 
# device = torch.device("cuda:0")
#torch.long and torch.float are the main tensor types
a = torch.tensor([-5, 7], dtype = torch.float)
b = torch.tensor([2, 1], dtype = torch.float)
print("a", a)
print("type tensor", a.dtype)
#sum of vectors
c = a + b
print("sum: ", c)
#substraction of vectors
d = a - b
print("subs: ", d)
#element wise division of vectors
e = a / b
print("elem. wise div.: ", e)
#element wise multiplication of vectors
f = a * b
print("elem. wise mult.: ", f)
#abs of vector
g = torch.abs(a)
print(g)
#concat vectors
vec_cat = torch.cat((a, b), dim = 0)
print("concatenated vec: ", vec_cat)


a tensor([-5.,  7.])
type tensor torch.float32
sum:  tensor([-3.,  8.])
subs:  tensor([-7.,  6.])
elem. wise div.:  tensor([-2.5000,  7.0000])
elem. wise mult.:  tensor([-10.,   7.])
tensor([5., 7.])
concatenated vec:  tensor([-5.,  7.,  2.,  1.])


## Dot product

The dot product between to matrices A and B, and vectors w and v, is calculated as follows:

In [2]:
import torch as torch

device = torch.device("cpu") 
# device = torch.device("cuda:0")

a = torch.tensor([2,3], dtype = torch.float)
print("a", a)
print("type tensor", a.dtype)

w = torch.tensor([1.0, 2.0, 3.0], device = device)
v = torch.tensor([5.0, 6.0, 7.0], device = device)
#to get tensor dimensions, we use shape
print(w.shape)
#Dot product
dotProduct = w.dot(v)
print("Dot product: ", dotProduct.item())
# Dot product of matrices
A = torch.tensor([[1, 2, 3],[1, 2, 3]])
B = torch.tensor([[5, 5],[6, 6],[7, 7]])
#dotProduct = A.dot(B) it doesnt work
#print("Dot product: ", dotProduct)

print("A", A)

print("B", B)




a tensor([2., 3.])
type tensor torch.float32
torch.Size([3])
Dot product:  38.0
A tensor([[1, 2, 3],
        [1, 2, 3]])
B tensor([[5, 5],
        [6, 6],
        [7, 7]])


## Matrix multiplication

Matrix multiplication C = A B can be interpreted as a dot product of the rows in A and the columns in B




In [3]:
C = A.mm(B)
print(C)

tensor([[38, 38],
        [38, 38]])


## Element wise multiplication of matrices

The element wise multiplication of matrices A and B result in a matrix C with same dimensions, and multiplies its entries.


In [ ]:
A = torch.tensor([[1, 2], [3, 0]])
B = torch.tensor([[5, 6], [7, 0]])
C = A * B
print(C)
#Element wise multiplication allows us to calculate dot product of matrices
#dot produt of matrices A and B
dotProduct = C.sum()
print("Dot product: ", dotProduct)

tensor([[ 5, 12],
        [21,  0]])
Dot product:  tensor(38)


## Auto grad in Pytorch

In [ ]:
import torch
#x = Variable(torch.tensor[1.0], requires_grad=True); 
x = torch.tensor([1.0], requires_grad=True)
y = 3*x**2
y.backward()
print("Gradient ", x.grad)

Gradient  tensor([6.])
