# Matrices in pytorch


-Dr. Saul Calderon.


# Importing dependencies

In [2]:
# Since Collab is being used, it is necessary to install Pytorch

import torch as torch

import numpy as np
from matplotlib import pyplot as plt
from mpl_toolkits.mplot3d import Axes3D
from matplotlib import cm

A = torch.tensor([[4.0, 9.3, 3.7, 5.1], [-2.0, 10, 8.3, 7.3]], dtype = torch.float)


print("A shape ", A.shape)
print("A before \n ", A)
A[0, :] = 1

print(A)


A shape  torch.Size([2, 4])
A before 
  tensor([[ 4.0000,  9.3000,  3.7000,  5.1000],
        [-2.0000, 10.0000,  8.3000,  7.3000]])
tensor([[ 1.0000,  1.0000,  1.0000,  1.0000],
        [-2.0000, 10.0000,  8.3000,  7.3000]])


In [4]:
B = A > 5
print("B \n ", B)

#indexacion logica
A[B] = 1000
print("A \n", A)

B 
  tensor([[False, False, False, False],
        [False,  True,  True,  True]])
A 
 tensor([[   1.,    1.,    1.,    1.],
        [   0., 1000., 1000., 1000.]])


## Mode

In [22]:
A = torch.tensor([2, 3, 3, 3, 1])
print(A.mode())

torch.return_types.mode(
values=tensor(3),
indices=tensor(3))


## Modifying the shape of a tensor

In [9]:
A = torch.tensor([[1, 2, 4]])
print("A shape ", A.shape)
a = A.squeeze()
print("a shape ", a.shape)

a = torch.rand(4)
print("a ", a)
A = a.view(2, 2)
print("A \n ", A)



A shape  torch.Size([1, 3])
a shape  torch.Size([3])
a  tensor([0.3518, 0.8506, 0.9581, 0.2364])
A 
  tensor([[0.3518, 0.8506],
        [0.9581, 0.2364]])


# Matrices for rewriting equations and functions

The following equation system:
$$\begin{array}{c}
4x_{1}-5x_{2}=-13\\
-2x_{1}+3x_{2}=9
\end{array}$$
can be rewritten interms of vectors and matrices as follows:
$$A\,\vec{x}=\overrightarrow{b}\Rightarrow\vec{x}=A^{-1}\overrightarrow{b}$$


In [5]:

def testSolveEquationSystem1():
    """
    Solve an equation system with one solution
    """
    A = torch.tensor([[4.0, -5.0], [-2.0, 3.0]])
    #create a 2d tensor even for vectors, to avoid to create 1dtensor type creation
    b = torch.tensor([[-13.0], [9.0]])
    Ainv = A.inverse()
    x = Ainv.mm(b)
    print(x)
    

def testSolveEquationSystem2():
    """
    Solve an equation system with multiple solutions (one row is linear combination of the other)
    """
    A = torch.tensor([[4.0, -5.0], [8.0, -10.0]])
    #create a 2d tensor even for vectors, to avoid to create 1dtensor type creation
    b = torch.tensor([[-13.0], [9.0]])
    Ainv = A.inverse()
    x = Ainv.mm(b)
    print(x)
    
    
testSolveEquationSystem2()
    

RuntimeError: Lapack Error getrf : U(2,2) is 0, U is singular at c:\programdata\miniconda3\conda-bld\pytorch-cpu_1532498166916\work\aten\src\th\generic/THTensorLapack.cpp:523

## Matrix indexing and concatenation
Tensors can be indexed using the slicing operators, and concatenated using the function cat

In [12]:
# Dot product of matrices doesnt exist for 2D Tensors
A = torch.tensor([[1, 2, 3],[10, 20, 30]])
B = torch.tensor([[5, 5],[6, 6],[7, 7]])

print("dims A", A.shape)
print("A_0,0", A[0,0].item())
#slicing
print("Segunda fila de A: ", A[1,0:2])
print("A \n:", A)

#WE RECOMMEND ALWAYS USE 2D TENSORS, EVEN IF IT IS A VECTOR
#dotProduct = A.dot(B) it doesnt work, it is defined for 1D tensors only. 
#SOME OPERATORS ARE DEFINED FOR 1D TENSORS ONLY, AND SOME OF THEM ARE DEFINED FOR 2D TENSORS



dims A torch.Size([2, 3])
A_0,0 1
Segunda fila de A:  tensor([10, 20])
A 
: tensor([[ 1,  2,  3],
        [10, 20, 30]])
C: 
  tensor([[ 1,  2,  3,  1,  2,  3],
        [10, 20, 30, 10, 20, 30]])


In [6]:
#Create a matrix C, concatenating the matrix A along its rows
A = torch.tensor([[1, 2, 3],[10, 20, 30]])

print("A \n ", A)
C = torch.cat((A, A), 1)

print("C: \n ", C)

A 
  tensor([[ 1,  2,  3],
        [10, 20, 30]])
C: 
  tensor([[ 1,  2,  3,  1,  2,  3],
        [10, 20, 30, 10, 20, 30]])


In [28]:
C[C > 20] = 5
print("C despues de indexacion logica y mod. \n ", C)
D = torch.tensor(C > 3) * torch.tensor(C <= 10) 
print("Matriz de indices logicos: \n ", D)


C despues de indexacion logica y mod. 
  tensor([[ 1,  0,  0,  1,  2,  3],
        [10, 20,  5, 10, 20,  5]])
Matriz de indices logicos: 
  tensor([[False, False, False, False, False, False],
        [ True, False,  True,  True, False,  True]])


C:\Users\saul1\AppData\Local\Temp/ipykernel_20256/2251813912.py:3: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  D = torch.tensor(C > 3) * torch.tensor(C <= 10)


In [15]:
A = torch.tensor([[1, 2, 3],[1, 2, 3]])
B = torch.tensor([[1, 1, 10]])

print("Indexacion logica \n", A > 5)
A[A > 2] = -10
print("A \n", A)
#Create a matrix C, concatenating the matrix A along its rows
C = torch.cat((A, B), 0)
print("C\n ", C)


Indexacion logica 
 tensor([[False, False, False],
        [False, False, False]])
A 
 tensor([[  1,   2, -10],
        [  1,   2, -10]])


RuntimeError: Sizes of tensors must match except in dimension 0. Expected size 3 but got size 4 for tensor number 1 in the list.

## Identity matrix and other useful matrices

In [8]:
# Create an identity matrix
Identity = torch.eye(3)
print(Identity)
M_diagonal = 6 * Identity
print("M diagonal \n", M_diagonal)

tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
M diagonal 
 tensor([[6., 0., 0.],
        [0., 6., 0.],
        [0., 0., 6.]])


In [10]:
#zeroes matrix
ZerosM = torch.zeros(3,3)
print("zeros ", ZerosM)

zeros  tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])


In [11]:
#ones matrix
OnesM = torch.ones(5,5)
print("ones: \n", OnesM)

ones: 
 tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])


In [12]:
A = torch.rand(3,3)
B = torch.rand(3,3)
print("A:\n", A)
print("B:\n ", B)

A:
 tensor([[0.0875, 0.8943, 0.5903],
        [0.6164, 0.9359, 0.8407],
        [0.6539, 0.1726, 0.8529]])
B:
  tensor([[0.5027, 0.6374, 0.6634],
        [0.2761, 0.1711, 0.3197],
        [0.4316, 0.2748, 0.3037]])


In [25]:
#Identity is the mult. neutral operand
Res1 = 5 * OnesM.mm(Identity)
print("res1 \n", Res1)
Res2 = 5 * OnesM.mm(OnesM)
print("res2 \n", Res2)

#Adding and substracting matrices
A = torch.rand(3,3)
B = torch.rand(3,3)
print("A:\n", A)
print("B:\n ", B)
print("A + B: \n", A + B)




Identity 
 tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
zeros  tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])
ones:  tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])
res1 
 tensor([[5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5.],
        [5., 5., 5., 5., 5.]])
res2 
 tensor([[25., 25., 25., 25., 25.],
        [25., 25., 25., 25., 25.],
        [25., 25., 25., 25., 25.],
        [25., 25., 25., 25., 25.],
        [25., 25., 25., 25., 25.]])
A:
 tensor([[0.0231, 0.1686, 0.8612],
        [0.5139, 0.1772, 0.2737],
        [0.3146, 0.1714, 0.9353]])
B:
  tensor([[0.9840, 0.8096, 0.9975],
        [0.2652, 0.1226, 0.0298],
        [0.2585, 0.7882, 0.4576]])
A + B: 
 tensor([[1.0071, 0.9783, 1.8587],
       

## Matrix Transpose
The transpose operation is only defined for 2D tensors

In [13]:
#Matrix transpose
A_mat = torch.rand(3,3)
print("Original matrix: \n", A_mat)
A_mat_trans = A_mat.transpose(0, 1)
print("Transposed Matrix \n", A_mat_trans)



Original matrix: 
 tensor([[0.8141, 0.5878, 0.9087],
        [0.2381, 0.7492, 0.0216],
        [0.3477, 0.0292, 0.0268]])
Transposed Matrix 
 tensor([[0.8141, 0.2381, 0.3477],
        [0.5878, 0.7492, 0.0292],
        [0.9087, 0.0216, 0.0268]])


In [19]:
#Transpose cannot work with 1D tensors
w = torch.tensor([1, 2, 3])
#check tensor type
print("Type 1D tensor: ", w.type(), w.shape)



#row vector in 2D tensor
w2Drow = w.reshape(-1, w.shape[0])
print("Type 2D Tensor ", w2Drow.type(), w2Drow.shape)

print("row vector ", w2Drow)

#transpose receives the first dim0 to switch, and the second dim1 to swap, usually 0,1 is the order
wDrowT = w2Drow.transpose(0, 1)

print("wDrowT \n ", wDrowT)


Type 1D tensor:  torch.LongTensor torch.Size([3])
Type 2D Tensor  torch.LongTensor torch.Size([1, 3])
row vector  tensor([[1, 2, 3]])


IndexError: Dimension out of range (expected to be in range of [-1, 0], but got 1)

## Symmetric Matrices
A squared matrix is symmetric if  $A=A^{T}$

In [17]:
def isSymmetric(A):
    """
    A: input matrix
    """
    At = A.transpose(0, 1)
    return (torch.all(A.eq(At)))
        
#check wether the external product of the same vector is symmetric
B = torch.tensor([[1, 5, 3], [2, 7, 9], [2, 1, 4]])
Bt = B.transpose(0, 1)

print("B \n ", B)
print("Bt \n ", Bt)

Sym1 = B + Bt
print("Sym1 \n", Sym1)

print(isSymmetric(Sym1))
 
    

B 
  tensor([[1, 5, 3],
        [2, 7, 9],
        [2, 1, 4]])
Bt 
  tensor([[1, 2, 2],
        [5, 7, 1],
        [3, 9, 4]])
Sym1 
 tensor([[ 2,  7,  5],
        [ 7, 14, 10],
        [ 5, 10,  8]])
tensor(True)


In [ ]:

C = torch.tensor([[3, 4, 4], [5, 6, 7], [4, 5, 6]])
Ct = C.transpose(0, 1)
Sym2 = C + Ct
print("Sym2")
print(Sym2)
print(isSymmetric(Sym2))



isSymmetric(externalProduct2)  

## Element wise multiplication of matrices

The element wise multiplication of matrices A and B result in a matrix C with same dimensions, and multiplies its entries.


In [18]:
import torch
A = torch.tensor([[1, 2], [3, 0]])
B = torch.tensor([[5, 6], [7, 0]])
C = A * B
print(C)
#Element wise multiplication allows us to calculate dot product of matrices
dotProduct = C.sum()

print("Dot product: ", dotProduct)

tensor([[ 5, 12],
        [21,  0]])
Dot product:  tensor(38)


## Trace of a matrix
Implement the calculation of the trace of a matrix without using fors

In [25]:
def calculate_trace(A):
    I_n = torch.eye(A.shape[0])
    D = I_n * A
    print("D\n ", D)
    return torch.sum(D)

A = torch.tensor([[1, 3, 5.0], [3.0, 7, 9], [9.0, 3.0, 2.0]])
trace_A = calculate_trace(A)
print("trace A", trace_A)

D
  tensor([[1., 0., 0.],
        [0., 7., 0.],
        [0., 0., 2.]])
trace A tensor(10.)


In [24]:
R = torch.tensor([[1, 2.0, 3], [5, 6, 7]])
G = torch.tensor([[10, 20.0], [20.0, 20.0], [5.0, 5.0]])
D = R.mm(G)
print("D ", D)
D_mul_element_wise = R * R
print("Multiplicacion element wise \n", D_mul_element_wise)



D  tensor([[ 65.,  75.],
        [205., 255.]])
Multiplicacion element wise 
 tensor([[ 1.,  4.,  9.],
        [25., 36., 49.]])


## Matrix flatenning
Matrix flatenning refers to create a column or row vector with all the elements within a matrix.
See more at http://deeplizard.com/learn/video/fCVuiW9AFzY

In [33]:
A = torch.tensor([[1, 2, 3],[6, 24, 32]])
print("A original \n", A)

Af= A.reshape(A.shape[0] * A.shape[1], -1)
print("A reshaped \n ", Af)

#if we want to remove one dimension of the tensor, we can use squeeze, transforming from 2D to 1D tensor
Afs = Af.squeeze()
print("Afs \n ", Afs)



A original 
 tensor([[ 1,  2,  3],
        [ 6, 24, 32]])
A reshaped 
  tensor([[ 1],
        [ 2],
        [ 3],
        [ 6],
        [24],
        [32]])
Afs 
  tensor([ 1,  2,  3,  6, 24, 32])


## Matrix multiplication

Product of two matrices $A\in\mathbb{R}^{m\times n}$ and $B\in\mathbb{R}^{n\times p}$ is given by:
$$
C=A\,B=\begin{bmatrix}- & \vec{a}_{1,:}^{T} & -\\
- & \vec{a}_{2,:}^{T} & -\\
 & \vdots\\
- & \vec{a}_{m,:}^{T} & -
\end{bmatrix}\,\begin{bmatrix}| & | & \ldots & |\\
\vec{b}_{1,:} & \vec{b}_{2,:} & \ldots & \vec{b}_{p,:}\\
| & | & \ldots & |
\end{bmatrix}=\begin{bmatrix}\vec{a}_{1,:}^{T}\vec{b}_{1,:} & \vec{a}_{1,:}^{T}\vec{b}_{2,:} & \cdots & \vec{a}_{1,:}^{T}\vec{b}_{p,:}\\
\vec{a}_{2,:}^{T}\vec{b}_{1,:} & \vec{a}_{2,:}^{T}\vec{b}_{2,:} & \cdots & \vec{a}_{2,:}^{T}\vec{b}_{p,:}\\
\vdots & \vdots & \ddots & \vdots\\
\vec{a}_{m,:}^{T}\vec{b}_{1,:} & \vec{a'}_{m}^{T}\vec{b}_{2,:} & \cdots & \vec{a}_{m,:}^{T}\vec{b}_{p,:}
\end{bmatrix}
$$


In [19]:
#extract one row
A = torch.tensor([[1, 2], [3, 0]])
B = torch.tensor([[5, 6], [7, 0]])

print("matriz A")
print(A)
print("matriz B")
print(B)

a = A[0, :]
# extract one column
b = B[:, 0]
#calculate dot product
c = torch.dot(a,b)
print("Dot product")
print(c)

print("C = A B")
C = A.mm(B)
print(C)

matriz A
tensor([[1, 2],
        [3, 0]])
matriz B
tensor([[5, 6],
        [7, 0]])
Dot product
tensor(19)
C = A B
tensor([[19,  6],
        [15, 18]])


## External product of vectors
For two vectors

$\overrightarrow{x}\in\mathbb{R}^{m\times1}$, $\overrightarrow{y}\in\mathbb{R}^{1\times n} $ is given by: 
$$
\vec{x}\:\vec{y}^{T}\in\mathbb{R}^{m\times n}=\begin{bmatrix}x_{1}\\
x_{2}\\
\vdots\\
x_{m}
\end{bmatrix}\begin{bmatrix}y_{1} & y_{2} & \cdots & y_{n}\end{bmatrix}=\begin{bmatrix}x_{1}y_{1} & x_{1}y_{2} & \cdots & x_{1}y_{n}\\
x_{2}y_{1} & x_{2}y_{2} & \cdots & x_{2}y_{n}\\
\vdots & \vdots & \ddots & \vdots\\
x_{m}y_{1} & x_{m}y_{2} & \cdots & x_{m}y_{n}
\end{bmatrix}$$

In [21]:
A = torch.tensor([[5.0], [2.0], [3.0]])
z = torch.ones(1, 3, dtype = torch.float)
C = A.mm(z)
print("C \n ", C)

#funcion repeat
C1 = A.repeat(1, 3)
print("C1 \n ", C1)

C 
  tensor([[5., 5., 5.],
        [2., 2., 2.],
        [3., 3., 3.]])
C1 
  tensor([[5., 5., 5.],
        [2., 2., 2.],
        [3., 3., 3.]])


In [0]:
#1x3 vector
a = torch.tensor([[1, 2, 3]])
#3x1 vector
b = torch.tensor([[5], [6], [7]])
#3x3 matrix
externalProduct = b.mm(a)

print(externalProduct)

#what happens if a elements are equal to b?
b = torch.tensor([[1], [2], [3]])
externalProduct2 = b.mm(a)

print("External product of the same vector", externalProduct2)



tensor([[ 5, 10, 15],
        [ 6, 12, 18],
        [ 7, 14, 21]])
External product of the same vector tensor([[1, 2, 3],
        [2, 4, 6],
        [3, 6, 9]])


# Matrix-vector product
$$
\overrightarrow{y}=A\,\overrightarrow{x}=\begin{bmatrix}| & | & \ldots & |\\
\vec{a}_{:,1} & \vec{a}_{:,2} & \ldots & \vec{a}_{:,n}\\
| & | & \ldots & |
\end{bmatrix}\,\begin{bmatrix}x_{1}\\
x_{2}\\
\vdots\\
x_{n}
\end{bmatrix}=\left[\vec{a}_{:,1}\right]x_{1}+\left[\vec{a}_{:,2}\right]x_{2}+\ldots+\left[\vec{a}_{:,n}\right]x_{n}.
$$

In [0]:
A = torch.tensor([[2, 3], [4, 5]])
x = torch.tensor([[2], [3]])
#linear combination of A's columns
#y = 2 [[2], [4]] + 3 [[3], [5]] = [[13], [23]]
y = A.mm(x)
print(y)

tensor([[13],
        [23]])


For any squared non symmetric matrix $A\mathbb{\in R}^{n\times n}$, we can build a symmetric matrix $A+A^{T}$ 


In [0]:
AnonSym = torch.tensor([[3, 7, 5], [7, 3, 4], [3, 2, 1]])
print(AnonSym)
Bsym = AnonSym + AnonSym.transpose(0, 1)
print(Bsym)
#check if it is symmetric
isSymmetric()

tensor([[3, 7, 5],
        [7, 3, 4],
        [3, 2, 1]])
tensor([[ 6, 14,  8],
        [14,  6,  6],
        [ 8,  6,  2]])


## Matrix Rank
Lineally dependent vectors  $\left\{ \vec{x}_{1},\vec{x}_{2},\ldots,\vec{x}_{n}\right\} \subset\mathbb{R}^{m}$
if at least one vector can be written as a lineal combination of any of the rest: 
$$
\vec{x}_{j}=\sum_{i=1}^{n-1}\alpha_{i}\vec{x}_{i}
$$

In [22]:
import torch 

A = torch.tensor([[1, 2, 3.0], [4, 5, 6], [7, 1, 2]])
#de rango completo o no singular o invertibles
rank_A = torch.linalg.matrix_rank(A)
print("rank_A ", rank_A)
# matriz no invertible, singular, o de rango incompleto
B = torch.tensor([[1, 2], [2, 4.0]])
print("rank_B ", torch.linalg.matrix_rank(B))


rank_A  tensor(3)
rank_B  tensor(1)


In [34]:
import torch
import numpy as np

#Rank of 10x10 identity matrix
Identity = torch.eye(10)
MatrixRank = np.linalg.matrix_rank(Identity.numpy())
print("Rango de matriz identidad")
print(MatrixRank)
#squared matrix with linear combination of rows, rank inferior than number of rows and columns
A = torch.tensor([[4.0, -5.0], [8.0, -10.0]])
matrixRank = torch.linalg.matrix_rank(A)
print("Matrix A rank ", matrixRank)
#squared matrix with independent rows
B = torch.tensor([[4.0, 3.0], [-2.0, -4.0]])
MatrixRank = torch.linalg.matrix_rank(B)
print("Matrix B rank ", MatrixRank)



Rango de matriz identidad
10
Matrix A rank  tensor(1)
Matrix B rank  tensor(2)


In [44]:
B.inverse()
A1 = torch.tensor([[1, 43, 5.0], [2, 81, 10.0], [31, 6, 9.0]])
matrixRank = torch.linalg.matrix_rank(A1)
print("Rango de la matriz ", matrixRank)
print(A1.inverse())
Identity = A1.mm(A1.inverse())
print("Identity \n", Identity)


Rango de la matriz  tensor(3)
tensor([[ 0.9164, -0.4890,  0.0342],
        [ 0.4000, -0.2000,  0.0000],
        [-3.4233,  1.8178, -0.0068]])
Identity 
 tensor([[ 1.0000e+00,  0.0000e+00,  2.2352e-08],
        [-3.8147e-06,  1.0000e+00,  4.4703e-08],
        [ 0.0000e+00,  0.0000e+00,  1.0000e+00]])


## Inverse Matrix
The inverse matrix satisfies $A^{-1}A=I=A\,A^{-1}$ and also
$\left(A\,B\right)^{-1}=B^{-1}A^{-1}.$

In [25]:
import torch 

A = torch.tensor([[1, 2, 3.0], [4, 5, 6], [7, 1, 2]])

B = torch.tensor([[1, 2], [2, 4.0]])
A_inv = A.inverse()
print("A_inv \n ", A_inv)
print("A inverse * A \n", A.mm(A_inv) )

A_inv 
  tensor([[-0.1905,  0.0476,  0.1429],
        [-1.6190,  0.9048, -0.2857],
        [ 1.4762, -0.6190,  0.1429]])
A inverse * A 
 tensor([[ 1.0000e+00,  0.0000e+00, -5.9605e-08],
        [ 0.0000e+00,  1.0000e+00, -1.7881e-07],
        [ 0.0000e+00,  0.0000e+00,  1.0000e+00]])


In [17]:
B_inv = B.inverse()

RuntimeError: inverse_cpu: The diagonal element 2 is zero, the inversion could not be completed because the input matrix is singular.

In [15]:

def checkInverseMatrixMultiplicationProperty(A, B):
    """
    Checks matrix inverse multiplication property
    A: squared, full rank, non singular, invertible matrix
    B: squared, full rank, non singular, invertible matrix
    """
    Ainv = A.inverse()
    Binv = B.inverse()
    C = A.mm(B)
    CinvLeft = C.inverse()
    
    
    multRight = Binv.mm(Ainv)
    
    #for floating matrices, sum of difference must be small 
    return torch.abs((CinvLeft - multRight).sum()) < 0.1e-5

B = torch.tensor([[4.0, -5.0], [-2.0, 3.0]])
C = torch.tensor([[3.0, 5.0], [1.0, 7.0]])
#lets verify the rank
rankC = np.linalg.matrix_rank(C.numpy())
print("Rank of C ", rankC)


print ("Property check: ", checkInverseMatrixMultiplicationProperty(B,C))
    

    
    
    
    

Rank of C  2
Property check:  tensor(1, dtype=torch.uint8)


## Pseudo inverse matrix
The following are very important properties:
1. $$ \left(A^{T}A\right)^{-1}A^{T}\approx A^{+} $$

2. $$\left(A^{T}A\right)^{+}A^{T}=A^{+}$$

In [27]:
import numpy as np
#Example of non invertible matrix
D = torch.tensor([[3.0, 5.0], [6.0, 10.0]])

Dpinv = torch.tensor(np.linalg.pinv(D.numpy()))
print("Dpinv \n", Dpinv)
Icuasi = D.mm(Dpinv)
print(" Icuasi \n ", Icuasi)



Dpinv 
 tensor([[0.0176, 0.0353],
        [0.0294, 0.0588]])
 Icuasi 
  tensor([[0.2000, 0.4000],
        [0.4000, 0.8000]])


In [28]:

Dt = D.transpose(0, 1)
Left = torch.tensor(np.linalg.pinv(Dt.mm(D).numpy())).mm(Dt)
print("Left property 2? \n", Left)
print("Right of property \n", Dpinv)

Left property 2? 
 tensor([[0.0176, 0.0353],
        [0.0294, 0.0588]])
Right of property 
 tensor([[0.0176, 0.0353],
        [0.0294, 0.0588]])


In [16]:
def checkPseudoInverseProperty1(A):
    """
    Check pseudo inverse property 1
    """
    Apinv = torch.tensor(np.linalg.pinv(A.numpy()))
    At = A.transpose(0, 1)
    left = At.mm(A).inverse().mm(At)
    
    
    return (torch.abs(left - Apinv).sum()) < 0.1e-5
  
def checkPseudoInverseProperty2(A):
    """
    Check pseudo inverse property 2
    Pytorch pinv implementation is not recommended for non invertible matrices
    """
    
    #Apinv = A.pinverse()
    Apinv = torch.tensor(np.linalg.pinv(A.numpy()))
    print(Apinv)
    
    At = A.transpose(0, 1)
    left = torch.tensor(np.linalg.pinv(At.mm(A).numpy())).mm(At)
  
    
    return torch.abs((left - Apinv)).sum() < 0.1e-5
    
    
#pseudo inverse of invertible matrix  
print("C matrix")
print(C)


Cinv = C.inverse()
Cpinv = C.pinverse()
print("Inverted C ", Cinv)
print("Pseudo inverted C", Cpinv)

I = C.mm(Cpinv)
print("C * Cpinv ", I)
#check pseudo inverse property for invertible matrix
checkPseudoInverseProperty1(C)

#pseudo inverse of non invertible square matrix
D = torch.tensor([[3.0, 5.0], [6.0, 10.0]])
Dpinv = torch.tensor(np.linalg.pinv(D.numpy()))

print("Dpinv")
print(Dpinv)
print("Check second property ")
print(checkPseudoInverseProperty2(D))

#D.inverse()
#the inverse property is not satisfied
I = D.mm(Dpinv)
print("Dinv * D ", I)
print("PINV ", Dpinv)
#check pseudo inverse property
print("Satisfies pseudo inverse property 1: ", checkPseudoInverseProperty1(C))
result = checkPseudoInverseProperty2(D)
print("Satisfies pseudo inverse property 2: ", result)




C matrix
tensor([[3., 5.],
        [1., 7.]])
Inverted C  tensor([[ 0.4375, -0.3125],
        [-0.0625,  0.1875]])
Pseudo inverted C tensor([[ 0.4375, -0.3125],
        [-0.0625,  0.1875]])
C * Cpinv  tensor([[1.0000, 0.0000],
        [0.0000, 1.0000]])
Dpinv
tensor([[0.0176, 0.0353],
        [0.0294, 0.0588]])
Check second property 
tensor([[0.0176, 0.0353],
        [0.0294, 0.0588]])
tensor(1, dtype=torch.uint8)
Dinv * D  tensor([[0.2000, 0.4000],
        [0.4000, 0.8000]])
PINV  tensor([[0.0176, 0.0353],
        [0.0294, 0.0588]])
Satisfies pseudo inverse property 1:  tensor(1, dtype=torch.uint8)
tensor([[0.0176, 0.0353],
        [0.0294, 0.0588]])
Satisfies pseudo inverse property 2:  tensor(1, dtype=torch.uint8)


## Vector projection
Projection of $\vec{y}\in\mathbb{R}^{n}$ over the vectors generated by the set of base vectors $\left\{ \vec{a}_{1},\vec{a}_{2},\ldots,\vec{a}_{m}\right\} \qquad\vec{a}_{i}\in\mathbb{R}^{n}$
$$
\textrm{proy}\left(\vec{y};\left\{ \vec{a}_{1},\vec{a}_{2},\ldots,\vec{a}_{m}\right\} \right)=\textrm{argmin}_{\vec{v}\in\textrm{espacioGenerado}\left(\left\{ \vec{a}_{1},\vec{a}_{2},\ldots,\vec{a}_{m}\right\} \right)}\left\Vert \vec{v}-\vec{y}\right\Vert _{2}.
$$
with the generated space given by the column space:
$$
\mathcal{C}\left(A\right)=\left\{ \vec{v}\in\mathbb{R}^{n}:\vec{v}=A\,\vec{x},\;\vec{x}\in\mathbb{R}^{m},\:A\in\mathbb{R}^{n\times m}\right\} 
$$

with the optimal solution given by:

$$
\textrm{proy}\left(\vec{y};A\right)=A\,\left(A^{T}A\right)^{-1}A^{T}\vec{y}
$$


### Example 1: Same number of base vectors $m$ and vector dimensionality $n$, lineally independent base vectors
Given the independent base vectors  $$\vec{a}_{1}=\begin{bmatrix}0.5\\
0\\
0
\end{bmatrix}, \vec{a}_{2}=\begin{bmatrix}0\\
0.25\\
0
\end{bmatrix},  \vec{a}_{3}=\begin{bmatrix}0\\
0\\
2
\end{bmatrix}$$
Calculate the projection vector  $\textrm{proy}\left(\vec{y};A\right)\in\mathbb{R}^{3}$ with $ \vec{y}=\begin{bmatrix}1\\
2\\
3
\end{bmatrix}$ and evaluate its error

In [1]:
import torch
def projectInvertible(y, A): 
  """
  y: column vector, 2d tensor
  A: n x m matrix, 2d tensor
  """
  At = A.transpose(0, 1)
  invMatrix = At.mm(A).inverse()
  return A.mm(invMatrix).mm(At).mm(y)

def calculateProjectionError(v, y):
  """
  Calcualte projection error by using the euclidian distance
  """
  return torch.norm(v - y, 2)
  
y = torch.tensor([[1.0], [2.0], [3.0]])
A = torch.tensor([[0.5, 0, 0], [0, 0.25, 0], [0, 0, 2]])

#calculate the projection
v_opt = projectInvertible(y,A)

print("Projected vector: ")
print(v_opt)
#calculate its error, which should be zero for invertible A, or lineally independent base vectors

print("Projection error: ")
error = calculateProjectionError(v_opt, y)
print(error)
#Calculate the array of coefficients x
x = A.inverse().mm(v_opt)
print("x: \n", x)

Projected vector: 
tensor([[1.],
        [2.],
        [3.]])
Projection error: 
tensor(0.)
x: 
 tensor([[2.0000],
        [8.0000],
        [1.5000]])


### Example 2: Same number of base vectors $m$ and vector dimensionality $n$, lineally dependent base vectors
$$
\vec{a}_{1}=\begin{bmatrix}0.5\\
0\\
0
\end{bmatrix}, \vec{a}_{2}=\begin{bmatrix}1\\
0\\
0
\end{bmatrix}  \vec{a}_{3}=\begin{bmatrix}0\\
1\\
2
\end{bmatrix}
$$
Calculate the projection vector  $\textrm{proy}\left(\vec{y};A\right)\in\mathbb{R}^{3}$ with $ \vec{y}=\begin{bmatrix}1\\
2\\
3
\end{bmatrix}$ and evaluate its error

In [1]:
import numpy as np
import torch
def projectNonInvertible(y, A): 
  """
  y: column vector, 2d tensor
  A: n x m matrix, 2d tensor
  """
  print("a")
  pinvMatrix = torch.tensor(np.linalg.pinv(A))
  print("pinvMat shape ", pinvMatrix.shape)
  #print("A shape ", A.shape)
  #print("y shape, ", y.shape)
  return A.mm(pinvMatrix).mm(y)

y = torch.tensor([[1.0], [2.0], [3.0]])
A = torch.tensor([[0.5, 0, 0], [1, 0, 0], [0, 1, 2]])
#calculate the projection


In [ ]:
projY_A = projectNonInvertible(y,A)

print("Projected vector")
print(projY_A)


In [ ]:
print("Projection error: ")
error = calculateProjectionError(projY_A, y)
print(error)

### Example 3: More base vectors $m$ than vector dimensionality $n$
With the following base vectors $$\vec{a}_{1}=\begin{bmatrix}0.5\\
0\\
0
\end{bmatrix}, \vec{a}_{2}=\begin{bmatrix}0\\
0.25\\
3
\end{bmatrix}, \vec{a}_{3}=\begin{bmatrix}0\\
0\\
2
\end{bmatrix}, \vec{a}_{4}=\begin{bmatrix}23\\
5\\
3
\end{bmatrix}$$

In [15]:
A = torch.tensor([[0.5, 0, 0, 23], [0, 0.25, 0, 5], [0, 3, 2, 3]])
#calculate the projection
projY_A = projectNonInvertible(y,A)
print("Projected vector")
print(projY_A)
print("Projection error: ")
error = calculateProjectionError(projY_A, y)
print(error)

pinvMat shape  torch.Size([4, 3])
A shape  torch.Size([3, 4])
y shape,  torch.Size([3, 1])
Projected vector
tensor([[1.0000],
        [2.0000],
        [3.0000]])
Projection error: 
tensor(5.8400e-07)


### Example 4: Less base vectors $m$ than vector dimensionality $n$
Given the following base vectors:

$$ \vec{a}_{1}=\begin{bmatrix}5\\
7\\
21
\end{bmatrix},  \vec{a}_{2}=\begin{bmatrix}0\\
13\\
9
\end{bmatrix}$$

In [4]:
A = torch.tensor([[5.0, 0.0], [7.0, 13.0], [21.0, 9.0]])
#calculate the projection
projY_A = projectNonInvertible(y,A)
print("Projected vector")
print(projY_A)
print("Projection error: ")
error = calculateProjectionError(projY_A, y)
print(error)

Projected vector
tensor([[0.5621],
        [1.9062],
        [3.1356]])
Projection error: 
tensor(0.4679)


## Example 5: Proyection over a vector 
Take the following vector to do the projection to: 
$$ \vec{a}_{1}=\begin{bmatrix}5\\
7\\
21
\end{bmatrix}$$

Using: 

$$
\textrm{proy}\left(\vec{y};\vec{a}\right)=\frac{\vec{a}\,\vec{a}^{T}}{\vec{a}^{T}\,\vec{a}}\vec{y}
$$

And 
$$
\left\Vert \textrm{proy}\left(\vec{y};\vec{a_{1}}\right)\right\Vert =\left|\frac{\vec{y}\cdot\vec{a_{i}}}{\left\Vert \vec{a_{i}}\right\Vert }\right|=\left\Vert \frac{\vec{a}_{i}\,\vec{a}_{i}^{T}}{\vec{a}_{i}^{T}\,\vec{a}_{i}}\vec{y}\right\Vert 
$$

In [6]:
a = torch.tensor([[5.0], [17.0], [21.0]])
print(y)
def project_vector_to_vector_1(y, a):
    coef_matrix = a.mm(a.transpose(0,1)) / a.transpose(0,1).mm(a)
    #the denominator is just the dot product to itself
    projected_vec = coef_matrix.mm(y).transpose(0, 1)    
    return projected_vec
 

print("Result of projected vector")
vec_proj_1 = project_vector_to_vector_1(y, a)
print(vec_proj_1)
print("Projection error:")
print(calculateProjectionError(vec_proj_1, y))

#Excersise, demonstrate such equality

tensor([[1.],
        [2.],
        [3.]])
Result of projected vector
tensor([[0.6755, 2.2967, 2.8371]])
Projection error:
tensor(3.6918)


## Determinant of a Matrix
The determinant of a matrix is computed as follows:

In [10]:
import torch
A = torch.tensor([[1.0, 4.0, 9.0], [7.0, 2.0, 5.0], [6.0, 8.0, 3.0]])
det_A = torch.det(A)
print("determinant of matrix A: ", det_A)
print(A)
print(A.transpose(0, 1).mm(A))

determinant of matrix A:  tensor(398.0000)
tensor([[1., 4., 9.],
        [7., 2., 5.],
        [6., 8., 3.]])
tensor([[ 86.,  66.,  62.],
        [ 66.,  84.,  70.],
        [ 62.,  70., 115.]])


## Eigenvectors and Eigenvalues
The eigenvectors and eigenvalues can be computed in pytorch as follows:


In [3]:
B = torch.tensor([[0.0, 1.0], [-2.0, -3.0]])
Eigen_values, Eigen_vectors = torch.eig(B ,eigenvectors=True)
print("EigenValues:\n ", Eigen_values)
print("Eigen_vectors:\n ", Eigen_vectors)


EigenValues:
  tensor([[-1.,  0.],
        [-2.,  0.]])
Eigen_vectors:
  tensor([[ 0.7071, -0.4472],
        [-0.7071,  0.8944]])
