In [4]:
import torch

X = torch.tensor([[1, 3], [2, 2.5], [3, 3.5], [4, 2.6], [4.7, 3.6]])
print("X \n ", X)

mean = torch.mean(X, dim = 0)
print("mean \n", mean)
X_mean_substracted = X - mean
print("X_mean_substracted \n", X_mean_substracted)


X 
  tensor([[1.0000, 3.0000],
        [2.0000, 2.5000],
        [3.0000, 3.5000],
        [4.0000, 2.6000],
        [4.7000, 3.6000]])
mean 
 tensor([2.9400, 3.0400])
X_mean_substracted 
 tensor([[-1.9400, -0.0400],
        [-0.9400, -0.5400],
        [ 0.0600,  0.4600],
        [ 1.0600, -0.4400],
        [ 1.7600,  0.5600]])


In [ ]:
import matplotlib.pyplot as plt


plt.scatter(X[:, 0], X[:, 1])
plt.show()